project:
  type: website
  output-dir: docs

website:
  title: "Rob Donnelly"
  description: "Rob Donnelly's personal website"
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.html
      - text: "Posts"
        href: posts.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Teaching"
        href: teaching.qmd
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/rodonn
      - icon: twitter
        href: https://twitter.com/robdonnelly47
format:
  html:
    theme: cosmo
    css: styles.css



